base:
  url: http://localhost:${APP_PORT}/

spring:
  application:
    name: soup-shortener-url
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: none
  cache:
    type: redis
  data:
    redis:
      host: redis
      port: ${REDIS_PORT}
  kafka:
    bootstrap-servers: http://kafka:${KAFKA_PORT}
  security:
    oauth2:
      resourceserver:
        jwt:
          #          issuer-uri: http://localhost:${KEYCLOAK_PORT}/realms/soup
          jwk-set-uri: http://keycloak:${KEYCLOAK_PORT}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs
keycloak:
  realm: ${KEYCLOAK_REALM}
  auth-server-url: http://keycloak:${KEYCLOAK_PORT}/auth
  resource: ${KEYCLOAK_CLIENT_ID}
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET}
  bearer-only: true
