base:
  url: http://localhost:8080/

spring:
  application:
    name: soup-shortener-url
  datasource:
    url: jdbc:postgresql://localhost:5432/link-shortener
    username: soup
    password: soup
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: none
