base:
  url: http://localhost:8080/

spring:
  application:
    name: soup-shortener-url
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: none
  cache:
    type: redis
  data:
    redis:
      host: redis
      port: ${REDIS_PORT}
  kafka:
    bootstrap-servers: http://kafka:29092
